apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: solgate
spec:
  entrypoint: entrypoint
  onExit: exit-handler
  templates:
    - name: entrypoint
      steps:
        - - name: lookup
            template: lookup
        - - name: sync
            template: sync

    - name: exit-handler
      steps:
        - - name: failure-handler
            template: failure-handler
            when: "{{workflow.status}} != Succeeded"

    - name: lookup
      container:
        image: solgate:latest
        command: ["solgate", "list"]
        args: ["-o", "/mnt/vol/filelist.json"]
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 250m
            memory: 100Mi
        volumeMounts:
          - name: config
            mountPath: /etc/solgate
          - name: workdir
            mountPath: /mnt/vol
      volumes:
        - name: config
          secret:
            secretName: "{{workflow.parameters.config}}"
      metrics:
        prometheus:
          - name: solgate_lookup_exit_code
            labels:
              - key: instance
                value: "{{workflow.parameters.config}}"
              - key: exit_code
                value: "{{exitCode}}"
            help: Exit code counter of lookup step by Solgate instance
            counter:
              value: "1"
          - name: solgate_lookup_duration
            labels:
              - key: instance
                value: "{{workflow.parameters.config}}"
            help: Duration gauge of lookup step by Solgate instance
            gauge:
              value: "{{duration}}"
          - name: solgate_lookup_count
            labels:
              - key: instance
                value: "{{workflow.parameters.config}}"
              - key: status
                value: "{{status}}"
            help: Status counter of lookup step by Solgate instance
            counter:
              value: "1"

    - name: sync
      container:
        image: solgate:latest
        command: ["solgate", "send"]
        args: ["-l", "/mnt/vol/filelist.json"]
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 250m
            memory: 100Mi
        volumeMounts:
          - name: config
            mountPath: /etc/solgate
          - name: workdir
            mountPath: /mnt/vol
      volumes:
        - name: config
          secret:
            secretName: "{{workflow.parameters.config}}"
      metrics:
        prometheus:
          - name: solgate_sync_exit_code
            labels:
              - key: instance
                value: "{{workflow.parameters.config}}"
              - key: exit_code
                value: "{{exitCode}}"
            help: Exit code counter of sync step by Solgate instance
            counter:
              value: "1"
          - name: solgate_sync_duration
            labels:
              - key: instance
                value: "{{workflow.parameters.config}}"
            help: Duration gauge of sync step by Solgate instance
            gauge:
              value: "{{duration}}"
          - name: solgate_sync_count
            labels:
              - key: instance
                value: "{{workflow.parameters.config}}"
              - key: status
                value: "{{status}}"
            help: Status counter of sync step by Solgate instance
            counter:
              value: "1"

    - name: failure-handler
      steps:
        - - name: get-host
            template: get-host
        - - name: notify
            template: notify
            arguments:
              parameters:
                - name: argo-ui-host
                  value: "{{steps.get-host.outputs.parameters.host}}"

    - name: get-host
      outputs:
        parameters:
          - name: host
            valueFrom:
              jsonPath: "{.spec.host}"
      resource:
        action: get
        manifest: |
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: argo-server

    - name: notify
      inputs:
        parameters:
          - name: argo-ui-host
      container:
        image: solgate:latest
        command: ["solgate", "report"]
        env:
          - name: WORKFLOW_FAILURES
            value: "{{workflow.failures}}"
          - name: WORKFLOW_NAME
            value: "{{workflow.name}}"
          - name: WORKFLOW_NAMESPACE
            value: "{{workflow.namespace}}"
          - name: WORKFLOW_STATUS
            value: "{{workflow.status}}"
          - name: WORKFLOW_TIMESTAMP
            value: "{{workflow.creationTimestamp}}"
          - name: ARGO_UI_HOST
            value: "{{inputs.parameters.argo-ui-host}}"

        volumeMounts:
          - name: config
            mountPath: /etc/solgate
      volumes:
        - name: config
          secret:
            secretName: "{{workflow.parameters.config}}"
      metrics:
        prometheus:
          - name: solgate_notify_exit_code
            labels:
              - key: instance
                value: "{{workflow.parameters.config}}"
              - key: exit_code
                value: "{{exitCode}}"
            help: Exit code counter of notify step by Solgate instance
            counter:
              value: "1"
          - name: solgate_notify_duration
            labels:
              - key: instance
                value: "{{workflow.parameters.config}}"
            help: Duration gauge of notify step by Solgate instance
            gauge:
              value: "{{duration}}"
          - name: solgate_notify_count
            labels:
              - key: instance
                value: "{{workflow.parameters.config}}"
              - key: status
                value: "{{status}}"
            help: Status counter of notify step by Solgate instance
            counter:
              value: "1"

  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

  metrics:
    prometheus:
      - name: solgate_count
        labels:
          - key: instance
            value: "{{workflow.parameters.config}}"
          - key: status
            value: "{{workflow.status}}"
        help: Status counter by Solgate instance
        counter:
          value: "1"
      - name: solgate_duration
        labels:
          - key: instance
            value: "{{workflow.parameters.config}}"
        help: Duration gauge by Solgate instance
        gauge:
          value: "{{workflow.duration}}"
