apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: solgate-tower-analytics-prod
  name: solgate-tower-analytics-prod
spec:
  schedule: "0 9 * * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    arguments:
      parameters:
        - name: config
          value: solgate-tower-analytics-prod
    workflowTemplateRef:
      name: solgate
