apiVersion: v1
kind: Secret
metadata:
    name: solgate-mms
stringData:
    source.creds.yaml: ENC[AES256_GCM,data:46lRyOLGLNpAdLXYqP/u2gt3qUPeZ9CvCdC4rO7Fokg9HHJzYq0zHhiPtgNnMpmv381wMN3D4xXFBfmRWkM3CHH0CnhxCMy3RfzmCOWizqDgRcC+LnWYp9eU+w1dvkUoTKd+D6f1zzo=,iv:cFsxv7OSBMDfCADczv4Ifp3kCoAqkPQLoB5M+olZs3c=,tag:cSZjWEaUfrEVIdXAeDRDYg==,type:str]
    destination.0.creds.yaml: ENC[AES256_GCM,data:ieTn8d1AT7wVY880Hkpz6mGskvJyQlmj1slD1Rx9YO7EPzMmsTxx307kPrnpkuZJf1rDEm3llE8vcBvlaDZER+IQtGcgiksRo+5sQIrnZviG+rUmd+SFB29NE5L8YJMwnim1fHk12HQ=,iv:w3GCjupKYRrKfhakn8y4cJkskVmo7JZiEgUQNjpfE+s=,tag:2XfHAmMBn9xtvwrZz2N2yA==,type:str]
    destination.1.creds.yaml: ENC[AES256_GCM,data:35TAtR7Hkb8RoKObo7IdOsdiuo0EgpwkUk0wlLyqLHhCuWiCeJOvWMNBNXmArqLZ1d31sFN/btQG7knGBjpvI5RW5wgv0tFsvL8/TR6DbnU9OCVV39AFFnHjM5mlgJDy4Hk/QhFZWp1SOp+BHVjepHa9grhRMGkQxPvy5Q==,iv:Vv7RN8eUP4UTxBbJPluFNX3OyUZbevPXwh4claaz6z0=,tag:1J/P0+byPUeCbofT7XrEkA==,type:str]
    config.yaml: |
        alerts_smtp_server: smtp.corp.redhat.com
        alerts_from: solgate-alerts@redhat.com
        alerts_to: data-hub-alerts@redhat.com, rhmoper@us.ibm.com

        source:
          endpoint_url: https://s3.amazonaws.com
          base_path: open-marketplace-prod

        destinations:
          - endpoint_url: https://s3.upshift.redhat.com
            base_path: DH-SECURE-MARKETPLACE-METERING/production_data

          - endpoint_url: https://s3.us-east.cloud-object-storage.appdomain.cloud
            base_path: rhm-metering-cos-bucket
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-12T18:11:24Z'
    mac: ENC[AES256_GCM,data:Fk5yg8gK2nKdYcQ5iikWLz7Z+5xf3IfOe/XHQFD0GRC926d3gmeybsa+J2+h+GEIT52GwJWwYeHZrn5v7YcAs9x3gMJ/Uzqe3B1ZDKGndb1381DXNIDiFBrIYvBPewK6PmVfCZxeChQhsLTJFFMrihTU3MalvplnoBmuPSmy6M4=,iv:no2gMy6V3bGCejW1tJljbKAhpzwEfptg2+6+8JrSiV8=,tag:CTnH5gHxFmtcMX2B22Jg7A==,type:str]
    pgp:
    -   created_at: '2020-12-18T11:46:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/U/DC/Dp4lns/sUHTeyn1RW80SK79frvSRLvGlUtOpMzF
            hf7W1C4Rx7FNz1Sn8gicPjCukZ/q8uVZYbfhWq5c42wKlNNBGoaGheQAsP4P2v2W
            ObQc8VACsi+psM3DBbzDy1+zHwVAdjfNK53avN4VXQGv3E4q7X180NTUFitJJoLN
            qZJxKKPKdI4Dv8RVHU4vhnfOsy9nxQ4mkrQm1tTZ5I+mBF020RgRRciynRx8rKI7
            mm65AyT4TSZubYg50bpSzDLu76fNfkoDDDeLxD6g3JKqwlVI0NS09jH0jQldQ4w+
            TZpp0o2QU/FEWTKe8pg4OUEtGiwJ20NbPmOM/IbJ+tJeAYbcb2aCxAxfxqLXYi8v
            hXKACBumBKb2aBiX/VwI0q7w5rVmWYfQHEF80d6d1CpuL0ufQ6hQWOUrvhp5tcMb
            wptMHdKivoKKRovwWdn3gp/+4YPo7enXFeCkudv1dQ==
            =bmpm
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2020-12-18T11:46:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5MpUvZdp4z9AQ/9ESbfWQylixzNgIdZjlxS3vJPrzkveITbWgc1mHzmya4H
            XMl8Q/Wvh2fyON0/CTLaMaPOPo5Yb74lfxw7yM5q5rwvS+Hl2AyS9ni6jDECItos
            w8+KOaKn9Mk2a0J2ewx3uRjvv2VCf6Y2NufikIv2OcbZbJtSGl7d2NXlPs1iQpkG
            73CPFvPhgg2QdSCI7ELQ7lMfx3Y3PGfgJhIriqK05ExFx5yidcf1ufwBKy+8g6N9
            XkXWEAlB7ohmaLOKjTnMTGbPfg3D+cQZSkScnyJYMF9Qmw9RSb+EEjTdBtfJauB1
            TuvV9kodqCtSlZLVuHIsW+A0ZoxVZW0pLvyHXOvpoDlw/Lhjyth0Re/IpvfhkQ63
            qiJnJCKk+tuyxWSbUtZDbstOvbAEZFAgxq2foqagmP/6rzTeN+IdNGj90a256/Lj
            epaHV/cRETJeDcOgkUgvfb6u6+C5nMBA7b77vV32i/4fevrEcqZ08GIBjwHoJvdB
            kf7dbUPWuqg+LDDGvZXwtyVERWAueqZ3ZS7yWk8EUdcCMw+aNaL3+VHpz4ep5xBX
            YvHbozLJvkTgOFrfx8UgOkUikysozzvZIfDZCemO/zJTfJAdcE0knP0VJMn7HsU9
            RfuIOyswpRjuR1i2X8NZ58HsUDKtFBZ3PuDG+gHDXY/SLUnRlNjjtWy8FfvafT3S
            XgFkl2gR6jfsVSVMkn8EZQGhr75HZoPGBvpNeuzdSBDbXTifSnolkns4rj2XQ6vb
            iv9foIfVnhDT3ctsRxG4wwtkYVmL637YJV0ivUDenve/TzmjAqbYhrxo+gL/V2E=
            =cCMp
            -----END PGP MESSAGE-----
        fp: A76372D361282028A99F9A47590B857E0288997C
    encrypted_regex: ^(.*.creds.yaml.*)$
    version: 3.6.1
