apiVersion: v1
kind: Secret
metadata:
    name: solgate-tower-analytics-stage
stringData:
    source.creds.yaml: ENC[AES256_GCM,data:GioYoACqtCYWgi32a4e32uiDs+Bbka7QRDcFL/oPq2EOCr2mokn/szCy+JWK4Fe8fvmS4W+uTtq6IuEHlM2C6RiOYUwvrtMxQbzYJzLVO6UGhH5opEtOQHTRj+8KTx4FYsFGhK4QqQg=,iv:FmNIjMYH5bZYbVg0DSrQfZ6A7A9NtTTyGke8riyZ+Rs=,tag:KVVxquysan6Sz99ilxVMIw==,type:str]
    destination.creds.yaml: ENC[AES256_GCM,data:iHX53G/god/nhMuckcKmqstqY3h6SdE1lRN5Dk3rrBPHE8+/ISTnBvmecvog1CV8BLM+6CoTKBJC0emWCUhZGjmZ4sSgV9fcIXm/xCCza6DbCu7t7chVigRSU9Nqe4VZBlH22geGi2w=,iv:6c3S5QUCDhqJzS+xQVP3GH7ew/NbeVSUHo43ngSfaAY=,tag:sEX5Sm1dtdOwD0mGV78JYQ==,type:str]
    config.yaml: |
        alerts_smtp_server: smtp.corp.redhat.com
        alerts_from: solgate-alerts@redhat.com
        alerts_to: tcoufal@redhat.com

        source:
          endpoint_url: https://s3.us-east-1.amazonaws.com
          base_path: tower-analytics-dbdumps-stage-s3

        destinations:
          - endpoint_url: https://s3.upshift.redhat.com
            base_path: DH-DEV-TOWER-ANALYTICS
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-27T10:06:53Z"
    mac: ENC[AES256_GCM,data:1n7PJCbK4Hjw7N0Efi5wxUc78Oe5tj68aehIaY0aNmqvcypmtj2KbKQI0zertt8jIarTHlbtJslpdmbJZ3bH55iZfuJDMvafoRJOaIy9K9jHGkdvQeQGy+6ptK/45aTJvSk7/phN+ldv+hu2yiLnS2Y9U0z8SOUZ66V2+R7VgwE=,iv:vgug/RMWCqipXlC+VwAR65W43aLxCRHascki24caEU4=,tag:DlurSV41dw3NsLQjUglIlQ==,type:str]
    pgp:
        - created_at: "2020-12-18T11:46:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf8DJtNjDerAzVsUtkjAC5eHr88k+WNZspP1J4MZwqpPO+d
            nxHC+ZrnnpH+6SfF3pP+pCYbE67OR/cP2nmHyuh2iGsQf5mlInF+OvqqkJ9tPrI8
            xhvkHq2GuxQx4jvCUfdUkE1vjVbiAYDlDc8ByeDbm1A7x22HF4JvgYgD5ok2mjrl
            Rqby2LucdQqt1lh4BX/8E+/Z3dW5EmmX7xiblsqE9ZYWl54fox5LUbJrhBzeM++I
            Mq2UpN6rRY4SDqJTbtOXdMcRnvztuYKB6if3FGKx8b/HPd3KEHg3ltLy2q9+Wbcv
            PKn9SFpmiX05VFE5GIW+HyvLuWNxEf3uUbeHwycYFdJeAb9rUFu7CUM/1JSyCvC3
            QbSq82+C/FIqXwrl0nIAWfxQxlrHnST65SxUKFgPnQ8OnxbmjIqHX5cJICUzqLqz
            e/snCcE9wcZzsZkBpfd22e/eHlY0l8AAqn/YpFezqA==
            =BkBN
            -----END PGP MESSAGE-----
          fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
        - created_at: "2020-12-18T11:46:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5MpUvZdp4z9ARAAh3Zl9B+yzRdZyBvmkYg4yAvLweK15nLSsyWdN9NCWbJF
            dfpcGRdiTk/rwGkEt+i7jMH2cVFG0mjLI2hQ/Gq8EY9Z6phES6b2V/+QeXEiRSP9
            Bk2UBwHoivHRN5Vs2sFMxO9NtQC7wV3wC/Aqt5f3a78nHl4lCHMwK0Sa4oyzX+cJ
            XgEng0neCbOy+P2fVfrGQMLdQuSTDWlVMCiNXeHUqODCo6OrFxRoCujqUhuEVwzt
            2+rHKCgJcCEThxAPNZhtgtOxO8FbqMXTZrauYAznv7ZfXmpCZfCRZF/0TPxlJMWL
            FFd7Brxie5wglCdlZYbA8VmrFUjPWNkygPxv7djRo4gKJ6zq475oiI69H5ob1abr
            FMLUnEMUNNLokHKwxHaXgQyxwKvqRlWIINqyNe/KAahbNdwX60zFeDQghYByrM8S
            fEvP77a72Y1i/yUufGKMoCJ6S4BPpK3ILQym62CScBOjAI7nsF9j8yUeDSyWCcl0
            uLCR8jqXre0Eu04gINJCwLhZfiGPNTzvushVCVEz7aeUT0DChLXrE/gk9/FoPXB4
            WUvKVGo73UysoCeAT6wmpL6HfeaFxYAuU8ryVlkN05yozYSuWthFJILVPb6we2dm
            eUDFSZttWkUEGJT/1b5szzv9eKxxphX+GaZMIJImqPtUjBrE5B3MViT2LXkB9XPS
            XgED1nS0GHBvc21xkosZf0Dtsf/ypp1ka1vvVn5N89deh+fiA+s2tPtxpPKeBR3F
            PL1+/7EamnzTP/TyCuUc1l1vGgxrih2CHxBiOJg+wJvzW19gSXnqElMutYxLep8=
            =1IjY
            -----END PGP MESSAGE-----
          fp: A76372D361282028A99F9A47590B857E0288997C
    encrypted_regex: ^(.*.creds.yaml.*)$
    version: 3.7.1
