apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: solgate-usir-stage
  name: solgate-usir-stage
spec:
  schedule: "15 16 * * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    arguments:
      parameters:
        - name: config
          value: solgate-usir-stage
    workflowTemplateRef:
      name: solgate
