apiVersion: v1
kind: Secret
metadata:
    name: solgate-usir-stage
stringData:
    source.creds.yaml: ENC[AES256_GCM,data:VazUWz5r4l2tITGO0rPUyvpese1/Flygy55TOCwuCTyjT3T30qM/FQwcMLmJ0GM/MqPhQLYn2JqcMNNHTGdn15w/Od7s5cynbqz54oj4AVNe5dRKbWKGL0kzxsq4K8ThaIu+F3yjSNU=,iv:HDhw19kvP5ltxJRVAgmN/61WGG0keckvPsavT4TQEN0=,tag:QjNQR9ltHCvXis8sX44Njw==,type:str]
    destination.creds.yaml: ENC[AES256_GCM,data:W2U59BtTzmgLizi5DxcHibJommWHK0n+wFkW5Ng7My1Cp3A6fw/VEXzTLxNleTQzK7rjpLjoqdzBeHr+5uYlqrgW9HnfBZlDkvwfAYsG8fbLFWZfWyUAfjs5onUUufAIMUsJIDWBCEE=,iv:iGx7f8riI/4ZZZ6yN1NcvVwYAslMxTXQ9G4whHkY0ec=,tag:4404qoPG8ucNbnhEJeKlZQ==,type:str]
    config.yaml: |
        alerts_smtp_server: smtp.corp.redhat.com
        alerts_from: solgate-alerts@redhat.com
        alerts_to: data-hub-alerts@redhat.com

        source:
          endpoint_url: https://s3.us-east-1.amazonaws.com
          formatter: "{date}/{collection}.{ext}"
          base_path: rhsm-subscriptions-egress-stage

        destinations:
          - endpoint_url: https://s3.upshift.redhat.com
            formatter: "{collection}/historic/{date}-{collection}.{ext}"
            base_path: DH-SECURE-USIR/stage_data
            unpack: yes

          - endpoint_url: https://s3.upshift.redhat.com
            formatter: "{collection}/latest/full_data.csv"
            base_path: DH-SECURE-USIR/stage_data
            unpack: yes
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-14T14:49:17Z"
    mac: ENC[AES256_GCM,data:gW1ZDpldRk6JzHFPw5aUhckM/EMalTEDJC68HwDAHXSAS6q693zqxxd/ZJI4FxaT4JjmzFn7xHSQJJ5KgDs0prl7DkhJHLCDrjPNlq4/7LHWZ57Sk/NyMuWRXgTEUVngPRCQ/b5wXvZIoYjn3k2bjZ7Yd1EaDac1E+ef8G1FMKA=,iv:6aEXokbCDX/aIldKmCfjDb9IrVyRrfuMMMjSUBeECKs=,tag:f5hBvhwrBGDEShMTC0r4rw==,type:str]
    pgp:
        - created_at: "2020-12-18T11:46:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf8DJtNjDerAzVsUtkjAC5eHr88k+WNZspP1J4MZwqpPO+d
            nxHC+ZrnnpH+6SfF3pP+pCYbE67OR/cP2nmHyuh2iGsQf5mlInF+OvqqkJ9tPrI8
            xhvkHq2GuxQx4jvCUfdUkE1vjVbiAYDlDc8ByeDbm1A7x22HF4JvgYgD5ok2mjrl
            Rqby2LucdQqt1lh4BX/8E+/Z3dW5EmmX7xiblsqE9ZYWl54fox5LUbJrhBzeM++I
            Mq2UpN6rRY4SDqJTbtOXdMcRnvztuYKB6if3FGKx8b/HPd3KEHg3ltLy2q9+Wbcv
            PKn9SFpmiX05VFE5GIW+HyvLuWNxEf3uUbeHwycYFdJeAb9rUFu7CUM/1JSyCvC3
            QbSq82+C/FIqXwrl0nIAWfxQxlrHnST65SxUKFgPnQ8OnxbmjIqHX5cJICUzqLqz
            e/snCcE9wcZzsZkBpfd22e/eHlY0l8AAqn/YpFezqA==
            =BkBN
            -----END PGP MESSAGE-----
          fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
        - created_at: "2020-12-18T11:46:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5MpUvZdp4z9ARAAh3Zl9B+yzRdZyBvmkYg4yAvLweK15nLSsyWdN9NCWbJF
            dfpcGRdiTk/rwGkEt+i7jMH2cVFG0mjLI2hQ/Gq8EY9Z6phES6b2V/+QeXEiRSP9
            Bk2UBwHoivHRN5Vs2sFMxO9NtQC7wV3wC/Aqt5f3a78nHl4lCHMwK0Sa4oyzX+cJ
            XgEng0neCbOy+P2fVfrGQMLdQuSTDWlVMCiNXeHUqODCo6OrFxRoCujqUhuEVwzt
            2+rHKCgJcCEThxAPNZhtgtOxO8FbqMXTZrauYAznv7ZfXmpCZfCRZF/0TPxlJMWL
            FFd7Brxie5wglCdlZYbA8VmrFUjPWNkygPxv7djRo4gKJ6zq475oiI69H5ob1abr
            FMLUnEMUNNLokHKwxHaXgQyxwKvqRlWIINqyNe/KAahbNdwX60zFeDQghYByrM8S
            fEvP77a72Y1i/yUufGKMoCJ6S4BPpK3ILQym62CScBOjAI7nsF9j8yUeDSyWCcl0
            uLCR8jqXre0Eu04gINJCwLhZfiGPNTzvushVCVEz7aeUT0DChLXrE/gk9/FoPXB4
            WUvKVGo73UysoCeAT6wmpL6HfeaFxYAuU8ryVlkN05yozYSuWthFJILVPb6we2dm
            eUDFSZttWkUEGJT/1b5szzv9eKxxphX+GaZMIJImqPtUjBrE5B3MViT2LXkB9XPS
            XgED1nS0GHBvc21xkosZf0Dtsf/ypp1ka1vvVn5N89deh+fiA+s2tPtxpPKeBR3F
            PL1+/7EamnzTP/TyCuUc1l1vGgxrih2CHxBiOJg+wJvzW19gSXnqElMutYxLep8=
            =1IjY
            -----END PGP MESSAGE-----
          fp: A76372D361282028A99F9A47590B857E0288997C
    encrypted_regex: ^(.*.creds.yaml.*)$
    version: 3.7.1
